//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernEncryption.Translations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernEncryption.Translations.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation.
        /// </summary>
        public static string ChannelHeading {
            get {
                return ResourceManager.GetString("ChannelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your chats.
        /// </summary>
        public static string ChannelsHeading {
            get {
                return ResourceManager.GetString("ChannelsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contacts.
        /// </summary>
        public static string ContactsHeading {
            get {
                return ResourceManager.GetString("ContactsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onboarding.
        /// </summary>
        public static string CryptedOnBoardingMessage {
            get {
                return ResourceManager.GetString("CryptedOnBoardingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter validation code..
        /// </summary>
        public static string EnterVoucherRequest {
            get {
                return ResourceManager.GetString("EnterVoucherRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input message.
        /// </summary>
        public static string InputMessage {
            get {
                return ResourceManager.GetString("InputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string MessageSnippetMoreSign {
            get {
                return ResourceManager.GetString("MessageSnippetMoreSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more members.
        /// </summary>
        public static string MoreMembers {
            get {
                return ResourceManager.GetString("MoreMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Chat.
        /// </summary>
        public static string NewChatCallToAction {
            get {
                return ResourceManager.GetString("NewChatCallToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        public static string NewGroupCallToAction {
            get {
                return ResourceManager.GetString("NewGroupCallToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please register..
        /// </summary>
        public static string RegisterRequest {
            get {
                return ResourceManager.GetString("RegisterRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string RegistrationHeading {
            get {
                return ResourceManager.GetString("RegistrationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendCallToAction {
            get {
                return ResourceManager.GetString("SendCallToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send PIN to email address..
        /// </summary>
        public static string SendPinToEmailCallToAction {
            get {
                return ResourceManager.GetString("SendPinToEmailCallToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your one-time PIN is:.
        /// </summary>
        public static string VoucherValidationEmailBodyBeforePin {
            get {
                return ResourceManager.GetString("VoucherValidationEmailBodyBeforePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DontSpy.
        /// </summary>
        public static string VoucherValidationEmailSenderName {
            get {
                return ResourceManager.GetString("VoucherValidationEmailSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-time PIN for the verification at DontSpy.
        /// </summary>
        public static string VoucherValidationEmailSubject {
            get {
                return ResourceManager.GetString("VoucherValidationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Validation.
        /// </summary>
        public static string VoucherValidationHeading {
            get {
                return ResourceManager.GetString("VoucherValidationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
    }
}
